## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Colors configuration -------------------------------------

[colors.primary]
background = "#1e222a"
foreground = "#c8ccd4"

[colors.normal]
black   = "#1e222a"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#abb2bf"

[colors.bright]
black   = "#545862"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#c8ccd4"
